### PR TITLE
User interface in Tic Tac Toe project

### PR DESCRIPTION
**Pull request by MahmoudBakr23**
- Gets players names
- Prints the game board
- Gets the players moves
- Updates the board with players marks (X, O)

### CODE REVIEW

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required :wrench:

You are going in the right direction, congrats on that. Now let us clarify some points before you start working on this milestone again.

1. The game should not work, it should only pretend to be working. You can use a random number with `rand` to decide if the game is a winning scenario or a draw scenario; don't forget that there are maximum 9 moves and a minimum of 5 moves.

```ruby
player_choice = gets.chomp
if move_is_valid?(player_choice)
  puts board # but don't change it, the state of the board doesn't matter for this milestone
else
  puts wrong_move_message
end
```

2. The program should display how the game output will look in all the different possible scenarios.

```ruby
if winner
  puts winner_message
elsif draw
  puts draw_message
end
```

3. The program asks for input, but it does nothing with it, it should check it though.

## What to do now?

Ask for another CRR (Code Review Request) after implementing the changes.

You can find me in slack as **srodrig**.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: However, some changes still need to be applied in order to get approval for this milestone. Check :arrow_down: 

##### Implementation details

* [ ] Inside the loop, each iteration deals with all actions for the current player (DRY rules, you should not repeat code for the two players inside the loop)
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with a variable instead of using a counter:

```ruby
game_on = true

# initial instructions for player
current_player = player_one
while game_on
  # loop for each move
  # instructions for current_player
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
else
 # switch current_player
  end
end
```
#### General
- **[REQUIRED]** The pull request is not showing any checks :red_circle: Kindly make the necessary changes to make the checks appear.
### That's it :relieved: When finished, kindly submit a code re-review :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Good job so far on this. 👌

However, you have not done any of the two changes requested in the last review. Please fix the requested changes.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by Dandush03** [comment]
# Status: Approved 🚀 

## Great Work Implementing Your Changes

## Good Luck in your next assignment

**Pull request merged**
